VPATH=../src/contiki_rosnode
CFLAGS+=-I../src -std=c99
OBJECTS=$(wildcard ../src/**/*.c)
HEADERS=$(wildcard ../src/**/*.h)

#TestMsgDecode: TestMsgDecode.o $(OBJECTS:.c=.o)
TestMsgDecode: Test.o TestComplex.o
